### ISSUE TITLE
Can't set fixed height of collapsible header 

### ISSUE THREAD

**Issue by Belobobr** [rollymaduk/react-native-collapsible-tab-header#3]
It seems that Collapsible: height(number | string)-default('30%') must someway handle fixed height. But currently it does't.

I make this hot fix in getHeight function:

`if (typeof(height) === 'string' && !height.contains('%')) {
        return parseFloat(height);
    }`

**Comment by rollymaduk** [comment]
@Belobobr  that's strange, because the function 
`parseFloat('30') === parseFloat('30%')` returns true, `parseFloat('30') === parseFloat(30)` also returns true, so I am not sure that the problem precipates from that issue in the getHeight function. perhaps if you can do an example repo with the problem you encountered we can get to the real cause of the bug.  You can also look up the [tests](https://github.com/rollymaduk/react-native-collapsible-tab-header/blob/master/src/helpers.test.js) to verify the logic
